trigger:
  - master  # Adjust branch if needed

pool:
  vmImage: 'windows-latest'

variables:
  angularPath: 'click2LearnInstructorClient'
  dotnetPath: 'click2learnserver'
  buildConfiguration: 'Release'
  dotnetPublishPath: '$(Build.ArtifactStagingDirectory)/dotnet'
  angularPublishPath: '$(Build.ArtifactStagingDirectory)/angular'

steps:

# Install Node.js
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

# Install Angular Dependencies
- script: |
    cd $(angularPath)
    npm install
  displayName: 'Install Angular Dependencies'

# Build Angular Project
- script: |
    cd $(angularPath)
    npm run build -- --configuration production
  displayName: 'Build Angular Project'

# Publish Angular Build Artifacts
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(angularPath)/dist/click2LearnInstructorClient'
    ArtifactName: 'angularBuild'
    publishLocation: 'Container'
  displayName: 'Publish Angular Build'

# Install .NET SDK
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '6.x'
  displayName: 'Install .NET 6 SDK'

# Restore .NET Dependencies
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '$(dotnetPath)/click2learnserver.csproj'
  displayName: 'Restore .NET Dependencies'

# Build .NET Project
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '$(dotnetPath)/click2learnserver.csproj'
    arguments: '--configuration $(buildConfiguration)'
  displayName: 'Build .NET Project'

# Publish .NET Application
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--configuration $(buildConfiguration) --output $(dotnetPublishPath)'
  displayName: 'Publish .NET Application'

# Publish .NET Build Artifacts
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(dotnetPublishPath)'
    ArtifactName: 'dotnetBuild'
    publishLocation: 'Container'
  displayName: 'Publish .NET Build'

# Deploy .NET API to Azure App Service
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'click2learnserviceconnection'
    appName: 'functionnclick2learm'
    package: '$(dotnetPublishPath)'
  displayName: 'Deploy .NET API to Azure App Service'

# Deploy Angular to Azure Static Web Apps (if using Static Web Apps)
- task: AzureStaticWebApp@0
  inputs:
    app_location: '$(angularPath)/dist/click2LearnInstructorClient'
    output_location: 'dist/click2LearnInstructorClient'
    azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN)
  displayName: 'Deploy Angular to Azure Static Web Apps'

