trigger:
  - master

pool:
  vmImage: 'windows-latest'

variables:
  angularPath: 'click2LearnInstructorClient'
  distPath: 'click2LearnInstructorClient/dist/click2-learn-instructor-client'

stages:
# ========================= FRONTEND CI STAGE =========================
- stage: Build
  displayName: 'Frontend Continuous Integration'
  jobs:
  - job: Frontend_CI
    displayName: 'Build Angular App'
    steps:

    - task: NodeTool@0
      inputs:
        versionSpec: '16.x'
      displayName: 'Install Node.js'

    - script: |
        cd $(angularPath)
        npm install
      displayName: 'Install Angular dependencies'

    - script: |
        cd $(angularPath)
        npm run build --configuration=production
      displayName: 'Build Angular project'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(distPath)'
        ArtifactName: 'angularBuild'
        publishLocation: 'Container'
      displayName: 'Publish Angular Build'

# ========================= FRONTEND CD STAGE =========================
- stage: Release
  displayName: 'Deploy to Development'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeploymentDevelopment
    pool:
      vmImage: 'ubuntu-latest'
    environment: Development
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadBuildArtifacts@0
            displayName: 'Download Angular Build'
            inputs:
              artifactName: 'angularBuild'
              downloadPath: '$(Pipeline.Workspace)/angularBuild'

          - script: ls -R $(Pipeline.Workspace)/angularBuild
            displayName: 'Verify Downloaded Files'

          - task: AzureWebApp@1
            displayName: 'Deploy to Azure App Service'
            inputs:
              azureSubscription: 'Azure subscription 1(aef278c8-489c-4b12-9673-67f8b443eec9)'
              appType: 'webAppLinux'
              appName: 'clic2learn-ui'
              package: '$(Pipeline.Workspace)/angularBuild'
              runtimeStack: 'NODE|16-lts'
