trigger:
- master

pool:
  vmImage: 'windows-latest'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    pool:
      vmImage: 'windows-latest'
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '16.x'
        displayName: 'Install Node.js 16.x'

      - script: |
          cd click2LearnInstructorClient
          npm install -g @angular/cli
          npm install
          ng build --configuration=production
        displayName: 'npm install and build'
        workingDirectory: '$(Build.SourcesDirectory)'

      - task: ArchiveFiles@2
        displayName: 'Archive files'
        inputs:
          rootFolderOrFile: '$(Build.SourcesDirectory)/click2LearnInstructorClient/dist/click2-learn-instructor-client'
          includeRootFolder: false
          archiveType: zip
          archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
          replaceExistingArchive: true

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
          ArtifactName: 'click2learn-ui'
          publishLocation: 'Container'


# ========================= FRONTEND CD STAGE =========================
- stage: Release
  displayName: 'Deploy to Development'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeploymentDevelopment
    pool:
      vmImage: 'ubuntu-latest'
    environment: Development
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadBuildArtifacts@0
            displayName: 'Download Angular Build'
            inputs:
              artifactName: 'angularBuild'
              downloadPath: '$(Pipeline.Workspace)'

          - task: AzureWebApp@1
            displayName: 'Deploy App Service'
            inputs:
              azureSubscription: 'Azure subscription 1(aef278c8-489c-4b12-9673-67f8b443eec9)'
              appType: 'webAppLinux'
              appName: 'clic2learn-ui'
              package: '$(Pipeline.Workspace)/angularBuild'
              runtimeStack: 'NODE|16-lts'
